### ISSUE TITLE
Agregar componente PorPaisComponent

### ISSUE THREAD

**Issue by afrancom2** [jaelEspinosa/Angular-paisApp#1]
https://github.com/jaelEspinosa/Angular-paisApp/blob/172f65c73de697ca4671edf2f0b80c523cf9a21a/src/app/app-routing.module.ts#L27

Agregar codigo:
```
...
  {
    path: '**',
    component: PorPaisComponent,
    redirectTo: ''
  }
...
```

**Comment by jaelEspinosa** [comment]
Muchas Gracias @afrancom2, yo lo solucione también, aunque de otra manera. Agregando hash en la ruta.

`
@NgModule({
  imports:[
    RouterModule.forRoot( routes,{
      useHash:true
    } )
`
